FROM node:20-alpine

WORKDIR /app

# Instalar dependencias necesarias para Prisma y librerías nativas
RUN apk add --no-libc-dev openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

EXPOSE 5555